# Generated by Django 4.1.6 on 2023-02-09 22:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="auction",
            name="image_url",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="auction",
            name="starting_bid",
            field=models.IntegerField(),
        ),
    ]
