# Generated by Django 4.1.6 on 2023-02-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_rename_date_auction_created_at_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="comment",
            field=models.TextField(default=False, max_length=500),
        ),
    ]
